/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data.management.system;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author x18377201
 */
public class MainInterfaceGUI extends javax.swing.JFrame {

    //Liams Code 
    
 //vars
    String id; 
    String fname;
    String lname;
    //date dateadd;
    //date appdate;
    String msge;   
    Person[] person;
    Person p;
    ArrayList <Person> pl = new ArrayList <>();
    
    
    //declare counter to keep track of how many items are put into the array
    int count;
    
    //Creates new form MainInterfaceGUI
    public MainInterfaceGUI() {
        initComponents();
    //maximize screen
        this.setExtendedState(MainInterfaceGUI.MAXIMIZED_BOTH); 
    //centers j frame
        this.setLocationRelativeTo(null);
    //creates array
        person = new Person[5];
		//start with it set at 0
        count = 0; 
    }
        
 
   
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Exit_btn = new javax.swing.JButton();
        clientid_lbl = new javax.swing.JLabel();
        fname_lbl = new javax.swing.JLabel();
        lname_lbl = new javax.swing.JLabel();
        gender_lbl = new javax.swing.JLabel();
        dateadd_lbl = new javax.swing.JLabel();
        appdate_lbl = new javax.swing.JLabel();
        clientid_tf = new javax.swing.JTextField();
        fn_tf = new javax.swing.JTextField();
        ln_tf = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        save_btn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        delete_btn1 = new javax.swing.JButton();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue-gradient-abstract-hd-wallpaper-1920x1080-4250 (1).png"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "First Name", "Last Name", "Gender", "Date Added", "Appointment Date"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 30, 695, 660);

        Exit_btn.setBackground(new java.awt.Color(255, 102, 102));
        Exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Exit_btn.setText("Exit");
        Exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_btn);
        Exit_btn.setBounds(40, 680, 110, 40);

        clientid_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clientid_lbl.setText("Client ID:");
        getContentPane().add(clientid_lbl);
        clientid_lbl.setBounds(50, 65, 75, 22);

        fname_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fname_lbl.setText("First Name:");
        getContentPane().add(fname_lbl);
        fname_lbl.setBounds(50, 128, 90, 22);

        lname_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lname_lbl.setText("Last Name:");
        getContentPane().add(lname_lbl);
        lname_lbl.setBounds(50, 198, 89, 22);

        gender_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gender_lbl.setText("Gender:");
        getContentPane().add(gender_lbl);
        gender_lbl.setBounds(50, 278, 62, 22);

        dateadd_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateadd_lbl.setText("Date Added:");
        getContentPane().add(dateadd_lbl);
        dateadd_lbl.setBounds(50, 358, 98, 22);

        appdate_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        appdate_lbl.setText("Appointment Date:");
        getContentPane().add(appdate_lbl);
        appdate_lbl.setBounds(50, 438, 149, 22);
        getContentPane().add(clientid_tf);
        clientid_tf.setBounds(175, 69, 305, 20);
        getContentPane().add(fn_tf);
        fn_tf.setBounds(175, 132, 305, 20);
        getContentPane().add(ln_tf);
        ln_tf.setBounds(175, 202, 305, 20);

        add_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_btn.setText("Add");
        add_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        getContentPane().add(add_btn);
        add_btn.setBounds(40, 600, 110, 31);

        edit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(edit_btn);
        edit_btn.setBounds(230, 600, 110, 31);

        delete_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn);
        delete_btn.setBounds(400, 600, 110, 31);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gender.setSelectedIndex(-1);
        getContentPane().add(gender);
        gender.setBounds(180, 280, 94, 20);

        save_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn);
        save_btn.setBounds(230, 680, 110, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue-gradient-abstract-hd-wallpaper-1920x1080-4250 (1).png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1310, 790);

        delete_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_btn1.setText("Delete");
        delete_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn1);
        delete_btn1.setBounds(400, 600, 110, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
//        Person p;
//        p = new Person();
//        
//         //get data from form
//        fname = fn_tf.getText();
//        lname = ln_tf.getText();
//        id = Integer.parseInt(clientid_tf.getText());
//        //dateadd = date_added.getDate();//
//        //appdate = app_date.getDate();//
//        
//        //send to BankAccount object
//        p.setFname(fname);
//        p.setLname(lname);
//        p.setId(id);
//       
//        
//        //put to array
//        person[count] = p;
//        //increase counter
//        count++;
//        
//        for(int i=0; i < person.length; i = i +1){
//            JOptionPane.showMessageDialog(null,"First Name:" +person[i].getFname());
//        }
//        
        //Liams Code
         DefaultTableModel model = (DefaultTableModel)table.getModel(); 
          //model.addRow(new Object[]{clientid_tf.getText(),fn_tf.getText(),
           //                       ln_tf.getText(), gender.getSelectedItem(),
             //                     date_added.getDate(),app_date.getDate()}); 
           
         
         model.addRow(new Object[]{clientid_tf.getText(),fn_tf.getText(),
                                  ln_tf.getText(), gender.getSelectedItem()});
                                  //date_added.getDate(),app_date.getDate()});
         
         id = clientid_tf.getText();
         fname = fn_tf.getText();
         lname = ln_tf.getText();
         //dateadd = date_added.getDate();
         //appdate = app_date.getDate();
         p = new Person(id, fname, lname);
         
         pl.add(p);
         
        
        //clear text
        clientid_tf.setText("");
        fn_tf.setText("");
        ln_tf.setText("");
        gender.setSelectedItem(null);
        //date_added.setDate(null);
        //app_date.setDate(null);
        
        
    }//GEN-LAST:event_add_btnActionPerformed
    
    private JFrame frame;
    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        //Liams Code
        //delete selected row
     frame = new JFrame("Delete");   
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to delete this file ?","Scheduling System",
                JOptionPane.YES_NO_OPTION ) !=JOptionPane.YES_NO_OPTION){
        } 
        else {
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            int SelectedRowIndex = table.getSelectedRow();
            model.removeRow(SelectedRowIndex);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void Exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btnActionPerformed
        //Exit Button Code:
        //Liams Code
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit ?","Scheduling System",
                JOptionPane.YES_NO_OPTION ) ==JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }            
    }//GEN-LAST:event_Exit_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        
        id = p.getId();
        
        clientid_tf.setText(id);
        
        fn_tf.setText(fname);
        
        ln_tf.setText(lname);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_btnActionPerformed

    private void delete_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_btn1ActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
            table.addMouseListener(new MouseAdapter(){
                
                @Override
                public void mouseClicked(MouseEvent e){
                    int i = table.getSelectedRow();
                    textId.setText(model.getValueAt(i, 0).toString());
                    textFname.setText(model.getValueAt(i, 1).toString());
                    textLname.setText(model.getValueAt(i, 2).toString());
                }
            });
                save_btn.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {
                      if(i >=0)
                        {
                        int i = table.getSelectedRow();
                        model.setValueAt(textId.getText(), i, 0);
                        model.setValueAt(textFname.getText(), i, 1);
                        model.setValueAt(textLname.getText(), i, 2);
                        }
                      else{
                          System.out.println("Update Error");
                      }
                    }
                });  
                
            
        
       // DefaultTableModel model = (DefaultTableModel)table.getModel(); 
          //model.addRow(new Object[]{clientid_tf.getText(),fn_tf.getText(),
           //                       ln_tf.getText(), gender.getSelectedItem(),
             //                     date_added.getDate(),app_date.getDate()}); 
           
         
        // model.addRow(new Object[]{clientid_tf.getText(),fn_tf.getText(),
            //                      ln_tf.getText(), gender.getSelectedItem()});
                                  //date_added.getDate(),app_date.getDate()});
       // id = clientid_tf.getText();
        // fname = fn_tf.getText();
         //lname = ln_tf.getText();
         //dateadd = date_added.getDate();
         //appdate = app_date.getDate();
        // p = new Person(id, fname, lname);
         
         //pl.add(p);
         
         //clear text
        //clientid_tf.setText("");
        //fn_tf.setText("");
        //ln_tf.setText("");
        //gender.setSelectedItem(null);
        //date_added.setDate(null);
        //app_date.setDate(null);
       // TODO add your handling code here:
    }//GEN-LAST:event_save_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterfaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterfaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterfaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterfaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterfaceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Exit_btn;
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel appdate_lbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel clientid_lbl;
    private javax.swing.JTextField clientid_tf;
    private javax.swing.JLabel dateadd_lbl;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton delete_btn1;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField fn_tf;
    private javax.swing.JLabel fname_lbl;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ln_tf;
    private javax.swing.JLabel lname_lbl;
    private javax.swing.JButton save_btn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
